[profile.default]
src = 'contracts'
out = 'foundry-out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path = 'forge-cache'
solc_version = '0.8.21'
optimizer = true
optimizer_runs = 1000
via_ir = true
evm_version = 'paris'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
